#!/usr/bin/php
<?php 
// install in $PATH (for example, /usr/local/bin/)

// paste2 [language] [description] <[file]

// In vim, type :X,Yw !paste2 [language] [description]
// where X and Y are your line range 
// X can also be ^ (beginning of file)
// Y can also be $ (end of file)
// or you can omit X,Y (all of file)

// Will provide the paste2.org link on STDOUT.

if (isset($argv[1]))
	$lang = $argv[1];
else
	$lang = "text";
if (isset($argv[2]))
	$desc = implode(' ', array_slice($argv, 2));
else
	$desc = "";

$fields = array(
	'lang' => $lang,
	'description' => $desc,
	'code' => trim(stream_get_contents(STDIN)),
	'parent' => 0,
);
$cont = "";
foreach ($fields as $k => $v) {
	$cont .= '&'.$k.'='.urlencode($v);
}
$cont = substr($cont, 1)."\r\n";
$len = strlen($cont);

$s = fsockopen('paste2.org', 80);
$out = "";
$out .= "POST /new-paste HTTP/1.1\r\n";
$out .= "Host: paste2.org\r\n";
$out .= "User-Agent: Paster/1.0\r\n";
$out .= "Content-Type: application/x-www-form-urlencoded\r\n";
$out .= "Content-Length: $len\r\n";
$out .= "Connection: Close\r\n";
$out .= "\r\n";
$out .= $cont;
$out .= "\r\n";

fwrite($s, $out);
while (!feof($s)) {
	$buf = fgets($s, 512);
	if (strpos($buf, "Location: ") !== FALSE) {
		echo "http://paste2.org".substr($buf, 10);
		break;
	}
}
